### ISSUE TITLE
Deleting last number of "interval in days" resets the value to zero

### ISSUE THREAD

**Issue by arturbosch** [dzikoysk/presence-of-mind#21]
Hi,
thanks for the app! I'm currently evaluating if it fits me.

When editing the interval in days, one always needs to delete the default zero after editing the interval.

Steps to reproduce:
1. Set interval in days to 1
2. Delete value, see how it automatically resets to 0
3. Write 2 and notice the value is now 20
4. One needs to delete the 0 in the end

Imo the usage could be smoother if step 4 would not occur.

**Comment by dzikoysk** [comment]
Thanks, I'm currently collecting feedback from a few friends that also found this app useful, so I'll make some breaking changes in the following days and I'll also try to look at this issue :)

**Comment by arturbosch** [comment]
Cool, should I open issues for further improvements or post it here ?

**Comment by dzikoysk** [comment]
New issues would be great per each feature/bug, but I see you've already did that, so... 😛
