### ISSUE TITLE
Repeatable tasks by day of week

### ISSUE THREAD

**Issue by arturbosch** [dzikoysk/presence-of-mind#24]
Instead of interval in days I would love to see seven small buttons to click the day of the week.

Like in the clock app but more minimal

![Screenshot_20220705-165036](https://user-images.githubusercontent.com/20924106/177356955-25b488cb-566c-4366-86af-7e564549a74d.jpg)

**Comment by dzikoysk** [comment]
Not sure if such small icons are best way to go (it's quite painful on smaller screens/resolutions), but for sure we'd benefit from something like an init date for interval, because currently it always starts from the day you've finished the last one

**Comment by dzikoysk** [comment]
I want to keep interval in days, so repetitive attribute will be a variant since the next release:

![obraz](https://user-images.githubusercontent.com/4235722/178169943-19fda825-f904-43b6-a630-92dafbaad2c8.png)
