### ISSUE TITLE
Quick edit task by pressing or long pressing the task

### ISSUE THREAD

**Issue by arturbosch** [dzikoysk/presence-of-mind#25]
Maybe supporting press to edit and long press to open a menu could replace the three dots (more minimal look?).

I love the swipe to mark as finished action.
Protonmail for example uses swipe left to delete and swipe right to mark as spam.

Maybe hiding the settings behind swipe left would work in addition to swipe right to complete task?

---

Another Idea I just had to simply the edit menu:
- remove the edit dots
- add swipe left to move to a new edit screen where task and subtasks can be edited all in one
- from this edit screen swiping right would save and close the task and we return to the list view.

**Comment by dzikoysk** [comment]
Long press to edit would be slightly incompatible with an interaction to reorder tasks, but I like the idea with swipe to right to edit task. It'll be available in the next release:

<img width="400" src="https://user-images.githubusercontent.com/4235722/177788259-3c813e91-7792-421d-aa92-36e6993e7fe4.png">

**Comment by arturbosch** [comment]
@dzikoysk really cool, looks good!

**Comment by dzikoysk** [comment]
Thanks, I also like the result, but due to the fact I'm literally rewriting half of app to apply changes from all issues, the release candidate will be delayed for a few days 😳
