### ISSUE TITLE
Clicking the add subtask button while writing the current new subtask will delete the previous input

### ISSUE THREAD

**Issue by arturbosch** [dzikoysk/presence-of-mind#34]
Steps to reproduce

1. Add a task
2. Add a subtask
3. Go to manage subtasks
4. Click plus and write some text
5. Click plus again and notice the previous text was deleted

**Comment by dzikoysk** [comment]
Hmm it worked, I probably changed sth in one of the latest commits 🤔

**Comment by dzikoysk** [comment]
Fixed in RC.6 :)

**Comment by arturbosch** [comment]
> Fixed in RC.6 :)

Thanks, can confirm it works :)!
