### ISSUE TITLE
Swipe far to trigger action

### ISSUE THREAD

**Issue by arturbosch** [dzikoysk/presence-of-mind#39]
Please take a look at the attached video. Some apps like GitHub or Red reader (reddit frontend) implement not only swipe to show the action but also trigger it if you swipe and hold the item longer.

I think this would improve the workflow as you don't need to swipe, remove the finger and then press the edit button for example.

https://user-images.githubusercontent.com/20924106/179411240-09ce8a88-ae28-41de-a93c-8a11eef5441e.mp4

**Comment by dzikoysk** [comment]
Yup, I've asked some friends about this lately and they also prefer full swipe for instant trigger 😅 It's on my todo list, maybe I'll be to add this to RC.7.
